spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: srivatsan  

    
server:  port: 2020  

management:  endpoints:    web:      exposure:        include:        - "*"
# ---

#spring:#  h2:#    console:#      enabled: true
#      path: /h2
#  datasource:#    url: jdbc:h2:file:C:/h2data/sample 
#    username: sa
#    password: 
#    driver-class-name:org.h2.Driver 
    